name: 'GitHub Utility'
description: 'Run a set of  GitHub Utility instructions'
author: jpshrader
inputs:
  instructions:
    description: 'List of instructions for Github Utility to complete'
    type: string
    required: true
  file_type:
    description: 'Type of file being read in'
    type: string
    required: true
  access_token:
    description: 'GitHub Api Access Token'
    type: string
    required: true

env:
  action_url: $GITHUB_ACTION_PATH

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: '${{env.action_url}}/${{action_url}}/${{GITHUB_ACTION_PATH}}/.github/workflows/github-utility'
      with:
        file_type: ${{ inputs.file_type }}
        access_token: ${{ inputs.access_token }}
        instructions: ${{ inputs.username }}
