name: 'GitHub Utility'
description: 'Run a set of  GitHub Utility instructions'
author: jpshrader
inputs:
  instructions:
    description: 'List of instructions for Github Utility to complete'
    type: string
    required: true
  file_type:
    description: 'Type of file being read in'
    type: string
    required: true
  access_token:
    description: 'GitHub Api Access Token'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: jpshrader/github-utilities
        path: utils
    - name: Install dependencies
      shell: python
      run: |
        python -m pip install --upgrade pip
        pip install -r ./utils/requirements.txt
    - name: Run application
      shell: python
      run: |
        python ./utils/main.py --instructions ${{ inputs.instructions }} --file_type ${{ inputs.file_type }} --access_token ${{ inputs.access_token }}
