'''Branch management service'''
from time import time
from github import Github, Branch, Repository, GithubException, PullRequest, UnknownObjectException

from github_services.user_service import get_current_user
from github_services.comparison_service import is_ahead_with_branch, is_branch_ahead_with_repo
from github_services.repo_service import get_repo_by_full_name
from github_services.pull_request_service import create_pull_request_by_repo
from github_services.branch_service import delete_branch_from_repo_by_branch, get_branch_from_list, create_branch_from_repo, get_branches_by_repo, merge_branches_from_repo, get_branch_from_repo

def branch_passes_filters(branch: Branch.Branch, include: list[str], exclude: list[str]):
    '''Determines whether a branch name is filtered by include/exclude rules'''
    include_passes = len(include) == 0
    exclude_fails = len(exclude) > 0

    for inc in include:
        inc = inc.strip()
        if inc == '' or inc.lower() in branch.name.lower():
            include_passes = True

    for ex in exclude:
        ex = ex.strip()
        if ex == '' or ex.lower() in branch.name.lower():
            exclude_fails = True

    return include_passes and not exclude_fails

# MERGE AND PR BRANCH
def merge_branch_and_pr(github: Github, repo_full_name: str, from_branch: str, to_branch: str, reviewers: list[str], labels: list[str], title: str) -> None:
    '''Opens a Pr to update a given branch'''
    new_from_branch = f'merge-{from_branch}-to-{to_branch}-{int(time())}'
    repo = get_repo_by_full_name(github, repo_full_name)

    try:
        get_branch_from_repo(repo, to_branch)
    except UnknownObjectException:
        print(f'SKIPPING: No branch {to_branch} found in {repo_full_name}')

    if is_branch_ahead_with_repo(repo, to_branch, from_branch):
        print(f'Changes found for {repo_full_name} ({to_branch} <= {from_branch}) - Opening PR...')

        try:
            create_branch_from_repo(repo, to_branch, new_from_branch)
            merge_branches_from_repo(repo, new_from_branch, from_branch, f'Merge {from_branch} to {new_from_branch}')

            pull_request = create_pr(github, repo, title, to_branch, new_from_branch, labels, reviewers)

            print(f'SUCCESS: PR for {repo_full_name} ({to_branch} <= {from_branch}) opened: {pull_request.url}!')
        except GithubException as exp:
            if exp.status == 409:
                pull_request = create_pr(github, repo, title, to_branch, from_branch, labels, reviewers)
                print(f'WARNING: PR for {repo_full_name} ({to_branch} <= {from_branch}) opened with merge conflicts: {pull_request.url}f')
            else:
                print(f'FAILURE: Unable to create PR for {repo_full_name} ({to_branch} <= {from_branch})! An unexpected error occurred')
        except:
            print(f'FAILURE: Unable to create PR for {repo_full_name} ({to_branch} <= {from_branch})! An unexpected error occurred')
    else:
        print(f'SKIPPING: No changes found for {repo_full_name} ({to_branch} <= {from_branch})')

# CREATE PR
def create_pr(github: Github, repo: Repository.Repository, title: str, to_branch: str, from_branch: str, labels: list[str], reviewers :list[str]) -> PullRequest.PullRequest:
    '''Creates a Pr with labels and reviewers'''
    pr_description = 'This PR was auto-generated by the [github-api-workflow](https://github.com/jpshrader/github-api-workflows#usage) tool'
    pull_request = create_pull_request_by_repo(repo, title, pr_description, to_branch, from_branch, is_draft=False)

    for label in labels:
        pull_request.add_to_labels(label)

    if len(reviewers) > 0:
        reviewers_to_request = []
        current_user = get_current_user(github)
        for reviewer in reviewers:
            if reviewer != current_user.login:
                reviewers_to_request.append(reviewer)
        pull_request.create_review_request(reviewers_to_request)

    return pull_request

# IDENTIFY UNPROTECTED BRANCHES
def identify_unprotected_branches(github: Github, repo_full_name: str, include: list[str] = None, exclude: list[str] = None) -> list[Branch.Branch]:
    '''Returns a list of branches that are empty (not ahead of target branch)'''
    repo = get_repo_by_full_name(github, repo_full_name)
    return identify_unprotected_branches_with_repo(repo, include=include, exclude=exclude)

def identify_unprotected_branches_with_repo(repo: Repository.Repository, include: list[str] = None, exclude: list[str] = None) -> list[Branch.Branch]:
    '''Returns a list of branches that are empty (not ahead of target branch)'''
    unprotected_branches = []
    branches = get_branches_by_repo(repo)
    for branch in branches:
        if not branch.protected and branch_passes_filters(branch, include, exclude):
            unprotected_branches.append(branch)

    return unprotected_branches

# IDENTIFY EMPTY BRANCHES
def identify_empty_branches(github: Github, repo_full_name: str, target_branch: str = '', include: list[str] = None, exclude: list[str] = None) -> list[Branch.Branch]:
    '''Returns a list of branches that are empty (not ahead of target branch)'''
    repo = get_repo_by_full_name(github, repo_full_name)
    return identify_empty_branches_with_repo(repo, target_branch, include=include, exclude=exclude)

def identify_empty_branches_with_repo(repo: Repository.Repository, target_branch: str = '', include: list[str] = None, exclude: list[str] = None) -> list[Branch.Branch]:
    '''Returns a list of branches that are empty (not ahead of target branch)'''
    if target_branch == '':
        target_branch = repo.default_branch

    empty_branches = []
    branches = get_branches_by_repo(repo)
    target = get_branch_from_list(branches, target_branch)

    for branch in branches:
        if target.name != branch.name and not(branch.protected) and not is_ahead_with_branch(repo, target, branch) and branch_passes_filters(branch, include, exclude):
            empty_branches.append(branch)

    return empty_branches

# DELETE EMPTY BRANCHES
def delete_empty_branches(github: Github, repo_full_name: str, target_branch: str, include: list[str] = None, exclude: list[str] = None) -> None:
    '''Deletes branches that are empty (not ahead of target branch)'''
    repo = get_repo_by_full_name(github, repo_full_name)
    branches = identify_empty_branches_with_repo(repo, target_branch, include, exclude)

    for branch in branches:
        delete_branch_from_repo_by_branch(repo, branch)
