'''Settings constants'''
PURGE_RULES     = 'purgeRules'
REPO_FILTERS    = 'repoFilters'
BRANCH_FILTERS  = 'branchFilters'
SETTINGS_FILE   = 'settings.json'
ACCESS_TOKEN    = 'gitHubApiAccessToken'
ITEMS_PER_PAGE  = 'gitHubApiItemsPerPage'
